name: Update github repo package
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  test:
    if: github.repository == 'underpostnet/pwa-microservices-template'
    name: Update github repo package Jobs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

        # - name: Get npm root
        #   run: sudo npm root -g

        # - run: npm ci

        # - name: Install underpost cli
        #   run: sudo npm install -g underpost

        # usage: git remote set-url [--push] <name> <newurl> [<oldurl>]
        #    or: git remote set-url --add <name> <newurl>
        #    or: git remote set-url --delete <name> <url>
        #     --[no-]push           manipulate push URLs
        #     --[no-]add            add URL
        #     --[no-]delete         delete URLs

      - name: Install dependencies and set repo configuration
        run: |
          npm install
          node ./bin/deploy rename-package @underpostnet/underpost
          node ./bin/deploy set-repo underpostnet/pwa-microservices-template-ghpkg

      - name: Set git credentials
        run: |
          git config --global credential.helper store
          git config --global user.name 'underpostnet'
          git config --global user.email 'fcoverdugoa@underpost.net'
          git config --global credential.interactive always
          git config credential.helper store
          git config user.name 'underpostnet'
          git config user.email 'fcoverdugoa@underpost.net'
          git config credential.interactive always

      - name: Push to github package repository
        run: |
          pwd
          git status
          git remote set-url origin https://${{ secrets.GIT_AUTH_TOKEN }}@github.com/underpostnet/pwa-microservices-template-ghpkg.git
          git add package.json
          git add package-lock.json       
          git commit -m "Update github repo package"
          git push -u origin master
