name: Update github repo package
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  test:
    if: github.repository == 'underpostnet/pwa-microservices-template'
    name: Update github repo package Jobs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '22.x'
      #     registry-url: 'https://npm.pkg.github.com'

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # - name: Get npm root
      #   run: sudo npm root -g

      - name: Install Dependencies
        run: npm install

      # - run: npm ci

      # - name: Install underpost cli
      #   run: sudo npm install -g underpost

      # usage: git remote set-url [--push] <name> <newurl> [<oldurl>]
      #    or: git remote set-url --add <name> <newurl>
      #    or: git remote set-url --delete <name> <url>
      #     --[no-]push           manipulate push URLs
      #     --[no-]add            add URL
      #     --[no-]delete         delete URLs

      - name: Update github repo package
        run: |
          node ./bin/deploy rename-package @underpostnet/underpost
          node ./bin/deploy set-repo underpostnet/pwa-microservices-template-ghpkg
          git status
          git config user.name 'underpostnet'
          git config user.email 'fcoverdugoa@underpost.net'
          pwd
          git remote set-url origin https://${{ secrets.GIT_AUTH_TOKEN }}@github.com/underpostnet/pwa-microservices-template-ghpkg.git
          git add package.json
          git add package-lock.json       
          git commit -m "Update github repo package"
          git push -u origin master
